- wolfSSL/mkdocs-ja.yml
This PR adds `asn__public_8h.md` to `mkdocs-ja.yml`, and adds a trailing slash to `site_dir: html/` to be consistent with other product manual mkdocs files.
This goes along with wolfSSL PR https://github.com/wolfSSL/wolfssl/pull/5934.
> Add asn__public_8h.md to mkdocs-ja.yml

- wolfSSL-JNI/mkdocs.yml
- wolfSSL-JNI/src/chapter01.md
- wolfSSL-JNI/src/chapter02.md
- wolfSSL-JNI/src/chapter03.md
- wolfSSL-JNI/src/chapter04.md
- wolfSSL-JNI/src/chapter05.md
- wolfSSL-JNI/src/chapter06.md
- wolfSSL-JNI/src/chapter07.md
- wolfSSL-JNI/src/chapter08.md
This PR fixes the wolfSSL JNI/JSSE documentation. Much of it was previously incorrectly formatted from the migration from the previous system.
This also updates documentation content.
> Fix up wolfSSL JNI/JSSE documentation and Markdown

- wolfTPM/Makefile
- wolfTPM/header-ja/group__TPM2__Proprietary.md
- wolfTPM/header-ja/group__wolfTPM2__Wrappers.md
- wolfTPM/header-ja/tpm2_8h.md
- wolfTPM/header-ja/tpm2__wrap_8h.md
- wolfTPM/mkdocs-ja.yml
- wolfTPM/src-ja/chapter01.md
- wolfTPM/src-ja/chapter02.md
- wolfTPM/src-ja/chapter03.md
- wolfTPM/src-ja/chapter04.md
- wolfTPM/src-ja/chapter06.md
This PR aims to add support for Japanese documentation to wolfTPM.
Prerequisites:
Japanese font sets must be installed in the system. ”Noto Sans CJK JP” is required. The font files(7 files) could be downloaded from
(https://github.com/googlefonts/noto-cjk/tree/main/Sans/OTF/Japanese).
How to generate Japanese documents:
Pass DOC_LANG=JA option to make in wolfTPM directory. By default, English documents will be generated.
> Add Japanese support for wolfTPM

- .github/workflows/build-check.yml
This should fix the GitHub Actions "Docs Build Test / build" test. Updates the apt sources before trying to install dependencies.
> Fix GitHub Docs Build Test

- wolfCrypt-JNI/Makefile
- wolfCrypt-JNI/mkdocs-ja.yml
- wolfCrypt-JNI/src-ja/chapter01.md
- wolfCrypt-JNI/src-ja/chapter02.md
- wolfCrypt-JNI/src-ja/chapter03.md
- wolfCrypt-JNI/src-ja/chapter04.md
- wolfCrypt-JNI/src-ja/chapter05.md
- wolfCrypt-JNI/src-ja/chapter06.md
- wolfCrypt-JNI/src-ja/chapter07.md
- wolfCrypt-JNI/src-ja/chapter08.md
This PR aims to add support for Japanese documentation to wolfCrypt-JNI.
Prerequisites:
Japanese font sets must be installed in the system. ”Noto Sans CJK JP” is required. The font files(7 files) could be downloaded from
(https://github.com/googlefonts/noto-cjk/tree/main/Sans/OTF/Japanese).
How to generate Japanese documents:
Pass DOC_LANG=JA option to make in wolfCrypt-JNI directory. By default, English documents will be generated.
> Add Japanese support for wolfCrypt-JNI

- wolfSSL-JNI/src/chapter03.md
- wolfSSL-JNI/src/chapter04.md
- wolfSSL-JNI/src/chapter05.md
- wolfSSL-JNI/src/chapter08.md
Add clarification that on some operating systems the libwolfssljni.so file that is created during compilation could be named libwolfssljni.jnilib. Additionally, update example instructions for ClientSSLSocket.java example so that people can run the example by following the instructions.
> Add clarification for file names and update example instructions

- wolfSSL-JNI/src/chapter04.md
Change line that should be added to java.security from "jce" to "jsse".
> Fix error in System Installation Instructions

- wolfSSL/src/appendix07.md
Added new subsection `Post-Quantum Stateful Hash-Based Signatures`  to appendix07.
New subsection covers stateful Hash-based Signature (HBS) schemes. Includes:
- Motivation for stateful HBS schemes (including NIST and NSA), and introduction to LMS/HSS.
- Supported parameter sets.
- Tables showing sig size and num of signatures vs parameter sets.
- Benchmarking data from my linux i7 (specs included in docs), for both multi-threaded and single-threaded hss lib builds.
Note: I wasn't sure whether this should go in a separate appendix, or in appendix07. I can update the rest of appendix07 or move this as needed.
> Add LMS/HSS signatures to documentation.

- wolfSSL/src-ja/appendix07.md
Apply document update in PR101 to Japanese version.
> Apply doc update to Japanese ver.

- wolfSentry/Makefile
- wolfSentry/mkdocs-ja.yml
- wolfSentry/mkdocs.yml
- wolfSentry/src-ja/chapter03.md
- wolfSentry/src/ChangeLog.md
- wolfSentry/src/README.md
- wolfSentry/src/chapter03.md
- wolfSentry/src/freertos-lwip-app.md
- wolfSentry/src/json_configuration.md
`wolfSentry/`: update with latest documentation from main project repository.
See https://github.com/wolfSSL/wolfsentry/pull/52
> 20230929-wolfsentry-doc-sync

- wolfSSL/src/chapter02.md
Adds documentation of new `WOLFSSL_APPLE_NATIVE_CERT_VALIDATION` macro, as well as improve documentation for existing system CA cert option (`--enable-sys-ca-certs` and `WOLFSSL_SYS_CA_CERTS`)
> add WOLFSSL_APPLE_NATIVE_CERT_VALIDATION and WOLFSSL_SYS_CA_CERTS

- wolfSentry/src/ChangeLog.md
- wolfSentry/src/json_configuration.md
wolfSentry release 1.6.1 doc update
merge with https://github.com/wolfSSL/wolfsentry/pull/59
> 20231118-wolfsentry-doc-sync

- Makefile
- README.md
- wolfSSL-FIPS-Ready/Makefile
- wolfSSL-FIPS-Ready/header.txt
- wolfSSL-FIPS-Ready/mkdocs.yml
- wolfSSL-FIPS-Ready/src/section01.md
- wolfSSL-FIPS-Ready/src/section02.md
- wolfSSL-FIPS-Ready/src/section03.md
- wolfSSL-FIPS-Ready/src/section04.md
Adding wolfssl fips ready guide documentation based on: https://www.wolfssl.com/docs/fips-ready-user-guide/
> Adding wolfSSL FIPS Ready Docs

- wolfSSL-Porting/src/section02.md
All links at the end of section02 "porting wolfSSL" where broken, so just added the correct markdown syntax to get it to work.
> Fixed broken links in section02.md

- wolfHSM/src/chapter02.md
- wolfHSM/src/chapter03.md
- wolfHSM/src/chapter04.md
- wolfHSM/src/chapter05.md
- wolfHSM/src/chapter07.md
- wolfHSM/src/chapter08.md
- renamed references to `crypto_context` to `whServerCryptoContext`
- stripped trailing whitespace from all files
> quick wolfHSM fix: renamed struct and whitespace cleanup

- Makefile
- wolfSSL-FAQ/Makefile
- wolfSSL-FAQ/header.txt
- wolfSSL-FAQ/mkdocs.yml
- wolfSSL-FAQ/src/section01.md
- wolfSSL-FAQ/src/section02.md
Created a wolfSSL-FAQ directory, All information came from [FAQ](https://www.wolfssl.com/docs/frequently-asked-questions-faq/#How_do_I_find_the_correct_CA_certificate_to_load_into_a_client_for_authenticating_a_SSL/TLS_server?) with slight modifications.
> Added wolfSSL-FAQ directory

- wolfHSM/Doxyfile
Only documents public client+server API functions. Tested locally and seems to render fine.
> wolfHSM: only document client and server headers

- wolfSSL/src-ja/appendix06.md
- wolfSSL/src/appendix06.md
The documented error code for `ASN_SELF_SIGNED_E` is inconsistent with wolfssl/wolfcrypt/error-crypt.h in the wolfssl repository. Update the documentation so that the error code matches wolfssl/wolfcrypt/error-crypt.h.
> Update Self-Signed Certificate Error Code

- wolfCrypt-JNI/Makefile
- wolfCrypt-JNI/mkdocs.yml
- wolfCrypt-JNI/src/chapter09.md
This PR adds Chapter 9 (KeyStore Implementations) to the wolfCrypt JNI/JCE Manual. Included is a JKS to WKS (WolfSSLKeyStore) migration guide.
> Add wolfJCE JKS to WKS Migration Guide

- wolfHSM/Doxyfile
- wolfMQTT/Doxyfile
- wolfMQTT/Doxyfile-ja
- wolfSSL/Doxyfile
- wolfSSL/Doxyfile-ja
- wolfTPM/Doxyfile
Fix warnings about `COLS_IN_ALPHA_INDEX` being deprecated
> Fix doxygen warnings

- wolfMQTT/header-ja/mqtt_client.h
fixed them.
```
/home/iwai/temp/documentation/wolfMQTT/header-ja/mqtt_client.h:393: warning: argument 'MqttDisconnect構造体へのポインター。NULLを指定しても可。' of command @param is not found in the argument list of MqttClient_Disconnect_ex(MqttClient *client, MqttDisconnect *disconnect)
/home/iwai/temp/documentation/wolfMQTT/header-ja/mqtt_client.h:400: warning: The following parameter of MqttClient_Disconnect_ex(MqttClient *client, MqttDisconnect *disconnect) is not documented:
parameter 'disconnect'
```
```
/home/iwai/temp/documentation/wolfMQTT/header-ja/mqtt_client.h:194: warning: argument 'cmd_timeout_ms　最大コマンド待ち時間（ミリ秒）' of command @param is not found in the argument list of MqttClient_Init(MqttClient *client, MqttNet *net, MqttMsgCb msg_cb, byte *tx_buf, int tx_buf_len, byte *rx_buf, int rx_buf_len, …
```
> Addressed doxygen warnings

- wolfSSL/src/chapter04.md
Adding a section to talk about the MAX32666 support added by this [wolfSSL PR](https://github.com/wolfSSL/wolfssl/pull/7777)
> Adding MAX32666 Support to Features/Hardware Accelerated Crypto

- .gitignore
- wolfSSL/src/chapter10.md
Adds details as related to `NO_WOLFSSL_SHA256_INTERLEAVE` introduced in https://github.com/wolfSSL/wolfssl/pull/7262
> Add NO_WOLFSSL_SHA256_INTERLEAVE info.

- wolfSSL/Doxyfile
- wolfSSL/Doxyfile-ja
This fixes the title in https://www.wolfssl.com/doxygen/ so that it doesn't say "My Project".
> Fix documentation title

- wolfEngine/src/chapter03.md
- wolfEngine/src/chapter10.md
Found that to use `wolfEngine` with `openSSH` via `openSSL` you need `--enable-openssh` when doing `./configure` during the `wolfEngine` setup, if this is not specified it will lead to a permissions error when trying to open things such as `/dev/random`.
There seems to be no documentation on this requirement.
This [line](https://github.com/wolfSSL/wolfEngine/blob/178f4dc3c1e1577054d7be05da3ce440e82d7ec0/configure.ac#L132) here is where its at in the configure for wolfEngine
> Updating need for --enable-openssh for wolfEngine

- wolfSentry/src/ChangeLog.md
wolfSentry: update for v1.6.3.
> 20250123-wolfsentry-doc-sync

- wolfSSL/src/chapter02.md
Confirmed with Kaleb. 
Fixes ZD 19394.
> GCM_TABLE_4BIT is FIPS validated.

- wolfBoot/src/appendix12.md
The issue where appendix12.md was not built in the PDF version has been resolved.
> fix heading levels (to correct TOC)

- wolfBoot/Makefile
- wolfBoot/mkdocs.yml
- wolfBoot/src/appendix14.md
- wolfBoot/src/chapter02.md
This was written by @miyazakh and translated into English by me.
> Added explanation about configuration options

- wolfSSL/src/chapter03.md
- wolfSSL/src/chapter04.md
Added protocol to clarify we are talking about protocol version in the second sentence of the wolfSSL Manual 4.2.3.
> Added more clarification in wolfSSL Manual 4.2.3

- wolfMQTT/src/chapter02.md
- wolfSSH/src/chapter03.md
In wolfSSH added clarity to wolfSSH scpclient to properly use the example for sending files to and from server. In wolfMQTT fixed a command that had a random '.' at the end of it.
> Added clarification for wolfSSH ch.3 wolfscp example and fixed a command in wolfMQTT ch.2

- Makefile
- wolfSSL-FIPS-FAQ/Makefile
- wolfSSL-FIPS-FAQ/header.txt
- wolfSSL-FIPS-FAQ/mkdocs.yml
- wolfSSL-FIPS-FAQ/src/section01.md
- wolfSSL-FIPS-FAQ/src/section02.md
Fixed a PDF build error, as well as syntax and typo.
> Add wolfSSL FIPS FAQ

- wolfSSL-FIPS-FAQ/src/section02.md
I corrected typos in FIPS 140-3 and wc_SetSeed_Cb().
> Edited typos

- wolfSSL/src/chapter04.md
Dependent on this PR https://github.com/wolfSSL/wolfssl/pull/9044
> update staticmemory section of the manual

- wolfSSL/src/appendix07.md
- wolfSSL/src/chapter04.md
Added summaries of ML-KEM and ML-DSA.
> Summaries of ML-KEM and ML-DSA

- wolfSSL/src/chapter02.md
Adds description of `WOLFSSL_ASN_TEMPLATE` option to chapter 2 of the docs. Important because this is set by default when using `./configure` but is not set in `user_settings.h` so the user needs to know about it
> Chapter02: add WOLFSSL_ASN_TEMPLATE build option description 

- wolfCrypt-JNI/src-ja/chapter01.md
- wolfCrypt-JNI/src-ja/chapter02.md
- wolfCrypt-JNI/src-ja/chapter03.md
- wolfCrypt-JNI/src-ja/chapter04.md
- wolfCrypt-JNI/src-ja/chapter05.md
- wolfCrypt-JNI/src-ja/chapter06.md
- wolfCrypt-JNI/src-ja/chapter07.md
- wolfCrypt-JNI/src-ja/chapter08.md
- wolfSSL-JNI/src-ja/chapter01.md
- wolfSSL-JNI/src-ja/chapter02.md
- wolfSSL-JNI/src-ja/chapter06.md
following https://github.com/wolfSSL/documentation/pull/142 .
Some URLs have been changed to the Japanese version.
> [JA] wolfSSL JNI/JSSE: update pass on existing manual contents

- wolfHSM/src/chapter03.md
Changed reference to wolfHSM examples directory instead of the old examples repo which has now been deleted.
> Changed refernce to examples directory instead of now deleted repo
